language: python
cache:
  directories:
    - "node_modules"
install:
  - "if [[ \"$GROUP\" == js ]] ; then pip install dash[dev] ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm -v ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm install ; fi"
  - "if [[ \"$GROUP\" == python-linting ]] ; then pip install black flake8 isort>=4.3.5 ; fi"
script:
  - "if [[ \"$GROUP\" == js ]] ; then npm run lint ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm run test ; fi"
  - "if [[ \"$GROUP\" == js ]] ; then npm run test:demo ; fi"
  - "if [[ \"$GROUP\" == python-linting ]] ; then black . --check ; fi"
  - "if [[ \"$GROUP\" == python-linting ]] ; then flake8 ; fi"
  - "if [[ \"$GROUP\" == python-linting ]] ; then isort -rc -c ; fi"
  - "if [[ \"$GROUP\" == python-test ]] ; then python -m compileall dash_bootstrap_components ; fi"
matrix:
  include:
    - python: 3.6
      env: GROUP=python-linting
    - python: 3.6
      env: GROUP=js
    - python: 2.7
      env: GROUP=python-test
    - python: 3.5
      env: GROUP=python-test
    - python: 3.6
      env: GROUP=python-test
